---
langs: [fr_FR, en_US]
baseurl: "/plugins-docs" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
- vendor
plugins:
- jekyll-paginate
- jekyll-seo-tag
title: "Limad44 Plugins Documentations"
description: "Ceci est la documentation des plugins créés par Limad44 pour la solution domotique Jeedom."
author: "Limad44"
image: https://www.jeedom.com/site/logo.png
www: https://www.jeedom.com/
blog: https://blog.jeedom.com/
forum: https://community.jeedom.com
market: https://market.jeedom.com
doc: https://doc.jeedom.com/